In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
arr=np.array([10,20,30,40,50])

In [6]:
print(arr)

[10 20 30 40 50]


In [7]:
print("Shape of the array:", arr.shape)

Shape of the array: (5,)


In [8]:
Series=pd.Series([1,2,3,4,5])

In [9]:
print(Series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [10]:
arr_d1=np.array([1,2,3,4,5,6,7,8,9,10])

In [11]:
arr_multiD=np.array([[10,20,30,40,50],[40,50,60,70,80]])

In [12]:
print(arr_d1)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(arr_multiD)

[[10 20 30]
 [40 50 60]]


In [14]:
arr_zero=np.zeros((4,5))

In [15]:
print(arr_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
arr_oness=np.oness((4,5))

AttributeError: module 'numpy' has no attribute 'oness'

In [ ]:
arr_oness=np.oness((4,5))